# Generated by Django 5.2.1 on 2025-06-30 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='waiting_data',
            new_name='waiting_user_data',
        ),
        migrations.AddField(
            model_name='user',
            name='current_event_data',
            field=models.JSONField(default=dict, help_text='Armazena os dados do evento atual que está sendo agendado ou editado'),
        ),
        migrations.AddField(
            model_name='user',
            name='waiting_event_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='is_active', default=True)),
                ('event_summary', models.CharField(max_length=255)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('attendees', models.JSONField(default=list, help_text='Lista de emails dos participantes')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('reminders', models.JSONField(default=list, help_text='Lista de lembretes para o evento em minutos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
