# Generated by Django 5.2.1 on 2025-07-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_waiting_data_user_waiting_user_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appointment_message_counter',
            field=models.IntegerField(blank=True, help_text='Baseado nesse contador será enviado o contexto da conversa sobre o agendamento para a LLM', null=True),
        ),
    ]
