# Generated by Django 5.2.1 on 2025-07-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_appointment_message_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appointment_message_counter',
            field=models.IntegerField(blank=True, default=0, help_text='Baseado nesse contador será enviado o contexto da conversa sobre o agendamento para a LLM'),
        ),
    ]
