# Generated by Django 5.2.1 on 2025-07-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_appointment_message_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialoguecontext',
            name='session_id',
        ),
    ]
